// Conversions

let score = undefined


let valueAfterConversion = Number(score)

// console.log(typeof valueAfterConversion)

// console.log(valueAfterConversion)

// "33" => 33
// "33abc" => NaN
// true => 1; false => 0

let isLoggedIn = "g"

let booleanisLoggedIn = Boolean(isLoggedIn)
// console.log(typeof booleanisLoggedIn);

// console.log(booleanisLoggedIn);

// 1=> true; 0 => false
// "" => false
// "hitesh" => true

let stringNumner = 90

let stringNumberConverted = String(stringNumner)
// console.log(typeof stringNumberConverted);

// ***************************************Operations*********************************************

let value = 3
let negValue = -value
// console.log(negValue)

/* 
console.log(2 + 2)
console.log(2 - 2)
console.log(2 * 2)
console.log(2 / 2)
console.log(2 % 2)
console.log(2 ** 3) 
*/

console.log("1" + 2) // Aise situation mei agar pehle string hoga toh uske baad ke saare values string me convert hokr fir print hoge
console.log(1 + "2") // Aise situation mei agar pehle number hoga toh uske baad ke saare values number me convert hokr fir print hoge

let x = 1
let y = ++x
console.log(x, y);

// Increment 1++ returns value 2:- the increment operator increments and returns the value before incrementing.
// Increment ++1 returns value 2 :- the increment operator increments and returns the value after incrementing.

